---
- name: Install MySQL client and server
  package:
    name: mysql-server
    state: present
  when: ansible_os_family == "Debian"

- name: Start MySQL service
  service:
    name: mysql
    state: started
  when: ansible_os_family == "Debian"

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
    update_password: always
